name: Terraform Destroy for AWS

on:
  workflow_dispatch: # Este evento permite ejecutar el workflow manualmente.

jobs:
  terraform-destroy:
    name: Terraform Destroy on AWS
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4

      # Configurar las credenciales de AWS usando los secretos
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Inicializar Terraform
      - name: Terraform Init
        run: terraform init

      # Validar el estado de Terraform
      - name: Terraform Validate
        run: terraform validate

      # Generar un plan de Terraform Destroy (opcional)
      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan-destroy

      # Ejecutar Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
